# Generated by Django 4.2.dev20220824103047 on 2022-09-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_user_alter_film_name_alter_film_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='user',
            new_name='number_of_user',
        ),
    ]
