# Generated by Django 4.0.5 on 2022-08-19 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='user',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
